#!/bin/bash
# tds-patch.sh — Generate patch via advpls cli
# Usage: tds-patch.sh <project> <resources> <patchName> [PTM|UPD|PAK]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/tds-discover.sh"
source "$SCRIPT_DIR/tds-credentials.sh"

generate_patch() {
    local project="$1"
    local resources="$2"
    local patch_name="$3"
    local patch_type="${4:-PTM}"

    # Resolve server config
    local server_id
    server_id=$(tds_get project "$project" serverId)
    if [ -z "$server_id" ]; then
        echo "ERRO: Projeto '$project' nao mapeado." >&2
        list_projects >&2
        return 1
    fi

    local address port secure build environment username server_name
    address=$(tds_get project "$project" address)
    port=$(tds_get project "$project" port)
    secure=$(tds_get project "$project" secure)
    build=$(tds_get project "$project" build)
    environment=$(tds_get project "$project" environment)
    username=$(tds_get project "$project" username)
    server_name=$(tds_get project "$project" name)

    # Get password
    if ! cred_exists "$server_id"; then
        echo "ERRO: Credenciais nao encontradas para servidor '$server_name' (id: $server_id)." >&2
        echo "Salve com: tds-credentials.sh save $server_id <senha>" >&2
        return 1
    fi
    local password
    password=$(cred_get "$server_id")
    if [ -z "$password" ]; then
        echo "ERRO: Falha ao descriptografar senha do servidor." >&2
        return 1
    fi

    # Patch output directory
    local patch_dir
    patch_dir=$(tds_get project "$project" patchDir)
    [ -z "$patch_dir" ] && patch_dir="/tmp"
    mkdir -p "$patch_dir"

    # Get advpls
    local advpls
    advpls=$(tds_get advplsPath)

    # Generate temp .ini
    local ini_file
    ini_file=$(mktemp /tmp/tds-patch-XXXXXX.ini)

    cat > "$ini_file" <<EOF
; Auto-generated by tds-patch.sh for project $project
showConsoleOutput=true

[auth]
action=authentication
server=$address
port=$port
secure=$secure
build=$build
environment=$environment
user=$username
psw=$password

[patchGen]
action=patchGen
fileResource=$resources
patchType=$patch_type
saveLocal=$patch_dir/
patchName=$patch_name
EOF

    echo "[TDS-CLI] Gerando patch em $server_name ($environment)..."
    echo "[TDS-CLI] Recursos: $resources"
    echo "[TDS-CLI] Destino: $patch_dir/"

    # Execute
    local output
    output=$("$advpls" cli "$ini_file" 2>&1)
    local exit_code=$?

    # Cleanup temp .ini
    rm -f "$ini_file"

    echo "$output"

    # Check result and rename with timestamp
    if echo "$output" | grep -q "Patch generated successfully"; then
        # Find the generated patch file (advpls names it patchName + date)
        # Look for most recent file matching the patch name pattern
        local newest
        newest=$(ls -t "$patch_dir"/${patch_name}*.ptm "$patch_dir"/${patch_name}*.upd "$patch_dir"/${patch_name}*.pak "$patch_dir"/custom*.ptm "$patch_dir"/custom*.upd "$patch_dir"/custom*.pak 2>/dev/null | head -1)

        if [ -n "$newest" ]; then
            local timestamp
            timestamp=$(date +%Y%m%d_%H%M%S)
            local ext="${newest##*.}"
            local new_name="${patch_name}_${timestamp}.${ext}"
            mv "$newest" "$patch_dir/$new_name"
            echo "[TDS-CLI] Patch gerado: $patch_dir/$new_name"
        else
            echo "[TDS-CLI] Patch gerado, mas nao foi possivel renomear automaticamente."
            echo "[TDS-CLI] Verifique a pasta: $patch_dir/"
        fi
        return 0
    else
        echo "[TDS-CLI] ERRO na geracao do patch." >&2
        return 1
    fi
}

# --- Main ---
if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
        echo "Uso: tds-patch.sh <PROJETO> <recurso1,recurso2> <nomePatch> [PTM|UPD|PAK]"
        exit 1
    fi
    generate_patch "$1" "$2" "$3" "${4:-PTM}"
fi
