#!/bin/bash
# tds-compile.sh — Compile source files via advpls cli
# Usage: tds-compile.sh <project> <file1[,file2,...]> [T|F]

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/tds-discover.sh"
source "$SCRIPT_DIR/tds-credentials.sh"

compile() {
    local project="$1"
    local files="$2"
    local recompile="${3:-T}"

    # Resolve server config from cache
    local server_id
    server_id=$(tds_get project "$project" serverId)
    if [ -z "$server_id" ]; then
        echo "ERRO: Projeto '$project' nao mapeado. Projetos disponiveis:" >&2
        list_projects >&2
        return 1
    fi

    local address port secure build environment username includes server_name
    address=$(tds_get project "$project" address)
    port=$(tds_get project "$project" port)
    secure=$(tds_get project "$project" secure)
    build=$(tds_get project "$project" build)
    environment=$(tds_get project "$project" environment)
    username=$(tds_get project "$project" username)
    includes=$(tds_get project "$project" includes)
    server_name=$(tds_get project "$project" name)

    # Get password (from DPAPI store)
    if ! cred_exists "$server_id"; then
        echo "ERRO: Credenciais nao encontradas para servidor '$server_name' (id: $server_id)." >&2
        echo "Salve com: tds-credentials.sh save $server_id <senha>" >&2
        return 1
    fi

    local password
    password=$(cred_get "$server_id")
    if [ -z "$password" ]; then
        echo "ERRO: Falha ao descriptografar senha do servidor." >&2
        return 1
    fi

    # Get advpls path
    local advpls
    advpls=$(tds_get advplsPath)

    # Generate temp .ini
    local ini_file
    ini_file=$(mktemp /tmp/tds-compile-XXXXXX.ini)

    cat > "$ini_file" <<EOF
; Auto-generated by tds-compile.sh for project $project
; Server: $server_name ($address:$port)
showConsoleOutput=true

[auth]
action=authentication
server=$address
port=$port
secure=$secure
build=$build
environment=$environment
user=$username
psw=$password

[compile]
action=compile
program=$files
recompile=$recompile
includes=$includes
EOF

    echo "[TDS-CLI] Compilando em $server_name ($environment)..."
    echo "[TDS-CLI] Arquivos: $files"

    # Execute
    local output
    output=$("$advpls" cli "$ini_file" 2>&1)
    local exit_code=$?

    # Cleanup temp file (contains password)
    rm -f "$ini_file"

    echo "$output"

    # Check result
    if echo "$output" | grep -q "compiled successfully"; then
        echo "[TDS-CLI] Compilacao concluida com sucesso!"
        return 0
    else
        echo "[TDS-CLI] ERRO na compilacao." >&2
        return 1
    fi
}

# --- Main ---
if [ "${BASH_SOURCE[0]}" = "$0" ]; then
    if [ -z "$1" ] || [ -z "$2" ]; then
        echo "Uso: tds-compile.sh <PROJETO> <arquivo1[,arquivo2]> [T|F]"
        exit 1
    fi
    compile "$1" "$2" "${3:-T}"
fi
